id: I697B9B03
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T19:40:43+00:00'
last_modified: '2022-06-09T04:36:04.473980+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30443
  title: བོད་ཀྱི་རིག་གནས་ལས་འཕྲོས་པའི་གཏམ་སྤྱི་ནོར་བློ་གསལ་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B56C:
      image_group_id: I01JW42
      title: Volume 1 of bod kyi rig gnas las 'phros pa'i gtam spyi nor blo gsal mgul
        rgyan
      total_pages: 454
      order: 1
      base_file: B56C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
