id: P007075
initial_creation_type: ocr
source_metadata:
  id: bdr:W30443
  title: བོད་ཀྱི་རིག་གནས་ལས་འཕྲོས་པའི་གཏམ་སྤྱི་ནོར་བློ་གསལ་མགུལ་རྒྱན།
  author: ''
  volumes:
    ff0714442c24415dbe85ae5ed11829c9:
      image_group_id: I01JW42
      title: ''
      volume_number: 1
      total_pages: 454
ebook_metadata:
  title: བོད་ཀྱི་རིག་གནས་ལས་འཕྲོས་པའི་གཏམ་སྤྱི་ནོར་བློ་གསལ་མགུལ་རྒྱན།
  author: ''
  sku: P007075
  cover: cover.jpg
  layers:
  - pagination
